### ISSUE TITLE
test.html server url is out of date

### ISSUE THREAD

**Issue by acksmaggart** [jmandel/fhir-js-client#1]
This is a small one, but the test server url in `dist/test.html` is out of date, I think. It gave me an error when I loaded the page. This test server url works though: `http://hl7connect.healthintersections.com.au/svc/fhir`

I thought it would be easier to post it here and let someone with more permissions push it up rather than going through a pull request.

**Comment by jmandel** [comment]
Thanks! Please see https://github.com/FHIR/fhir.js for the maintained version of this library.

**Comment by acksmaggart** [comment]
Aha! Thanks
